### ISSUE TITLE
Getting Started Improvements

### ISSUE THREAD

**Issue by walkerlj0** [bacalhau-project/docs.bacalhau.org#26]
Problem Statement: Users who are new to Bacalhau and what it does need more context and walk through of the experience with doing some basic tasks with the CLI

Suggested Solution: [See the PR here for suggestions](https://github.com/bacalhau-project/docs.bacalhau.org/pull/25
)

**To-Dos**

- [x] Check how verbose output is after `docker container run`- <img width="672" alt="Screen Shot 2022-09-08 at 1 43 39 PM" src="https://user-images.githubusercontent.com/66978602/189208497-9f7716c7-1cb1-4337-938a-d8ddfcde35b4.png">
- [x] audit step where job ID is grabbed from process ID - <img width="817" alt="Screen Shot 2022-09-08 at 2 00 11 PM" src="https://user-images.githubusercontent.com/66978602/189208479-26027bfb-f646-4cf1-b55e-e82368992435.png"><img width="672" alt="Screen Shot 2022-09-08 at 1 43 39 PM" src="https://user-images.githubusercontent.com/66978602/189208483-d88e512e-f36a-4ff5-a779-8cdcb613cf38.png">
- [x] Add more context as indicated in PR above

**Comment by enricorotundo** [comment]
Thanks for reporting this!

**Comment by enricorotundo** [comment]
Fixed by 4f636c0f610baa634249c6d34688c1db86bb158e
Thanks again!
